services:
  # Web app (Flask UI)
  web:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - FLASK_APP=tm2tb/api/app.py
      # optional: host/port if your app uses them
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  # CLI / dev toolbox (no default command)
  tm2tb:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1

  # Test runner
  test:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: pytest -q
    environment:
      - PYTHONUNBUFFERED=1
