x-cache-env: &cache-env
  HF_HOME: /cache/hf                  # Hugging Face hub (models/datasets)
  TRANSFORMERS_CACHE: /cache/hf       # transformers also respects this
  SENTENCE_TRANSFORMERS_HOME: /cache/st
  XDG_CACHE_HOME: /cache/xdg          # default cache root for many libs
  TORCH_HOME: /cache/torch            # torch.hub, etc.
  PYTHONUNBUFFERED: "1"

services:
  # API service
  web:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - FLASK_APP=tm2tb/api/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  # CLI / dev toolbox (no default command)
  tm2tb:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
      - ./cache:/cache
    environment:
      <<: *cache-env

  # Test runner
  test:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./cache:/cache
    command: pytest -q
    environment:
      <<: *cache-env