version: "3.9"
services:
  tm2tb:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app             # live-reload your code
      - ./data:/data        # mount corpora/TMX here if you want
    environment:
      - FLASK_ENV=development
